#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript

#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH -C gpu
#SBATCH --gpus-per-task=1
#SBATCH -q regular
#SBATCH -J TRAIN
#SBATCH --mail-user=tom.m.linker@gmail.com
#SBATCH --mail-type=ALL
#SBATCH -A m5047
#SBATCH --mem=0
#SBATCH -t 12:0:0
source ~/.bashrc
conda activate mynequip
srun -n 1 nequip-train -cn train.yaml

