model:
  _target_: nequip.model.NequIPGNNModel
  avg_num_neighbors: 89.01878932696137
  per_type_energy_shifts: -5.201448296064995
  per_type_energy_scales:
    O: 0.8089376256532871
    H: 0.5689998484674563
  seed: 456
  model_dtype: float32
  type_names:
  - O
  - H
  r_max: 6.0
  num_features: 128
  num_layers: 2
  l_max: 1
  parity: true
  pair_potential:
    _target_: nequip.nn.pair_potential.ZBL
    units: metal
    chemical_species:
    - O
    - H
  compile_mode: compile
optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    factor: 0.6
    patience: 25
    min_lr: 0.0001
    threshold: 0.02
    threshold_mode: rel
  monitor: val0_epoch/weighted_sum
  interval: epoch
  frequency: 1
loss:
  _target_: nequip.train.EnergyForceLoss
  per_atom_energy: true
  coeffs:
    total_energy: 1.0
    forces: 1.0
train_metrics: null
val_metrics:
  _target_: nequip.train.EnergyForceMetrics
  coeffs:
    total_energy_rmse: 1.0
    per_atom_energy_rmse: null
    forces_rmse: 1.0
    total_energy_mae: null
    per_atom_energy_mae: null
    forces_mae: null
test_metrics:
  _target_: nequip.train.EnergyForceMetrics
  coeffs:
    total_energy_rmse: 1.0
    per_atom_energy_rmse: null
    forces_rmse: 1.0
    total_energy_mae: null
    per_atom_energy_mae: null
    forces_mae: null
num_datasets:
  train: 1
  val: 1
  test: 1
  predict: 0
info_dict:
  versions:
    torch: 2.9.1
    e3nn: 0.5.8
    nequip: 0.16.1
  data:
    _target_: nequip.data.datamodule.ASEDataModule
    seed: 456
    split_dataset:
      file_path: 16e.xyz
      train: 0.8
      val: 0.1
      test: 0.1
    transforms:
    - _target_: nequip.data.transforms.NeighborListTransform
      r_max: 6.0
    - _target_: nequip.data.transforms.ChemicalSpeciesToAtomTypeMapper
      model_type_names:
      - O
      - H
      chemical_species_to_atom_type_map:
        H: H
        O: O
    train_dataloader:
      _target_: torch.utils.data.DataLoader
      batch_size: 4
      num_workers: 1
      shuffle: true
    val_dataloader:
      _target_: torch.utils.data.DataLoader
      batch_size: 4
      num_workers: 1
    test_dataloader:
      _target_: torch.utils.data.DataLoader
      batch_size: 4
      num_workers: 1
    stats_manager:
      _target_: nequip.data.CommonDataStatisticsManager
      type_names:
      - O
      - H
  trainer:
    _target_: lightning.Trainer
    devices: 1
    max_epochs: 1000
    accelerator: gpu
    enable_checkpointing: true
    check_val_every_n_epoch: 1
    log_every_n_steps: 10
    callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      dirpath: /global/cfs/cdirs/m5047/train_sam/nequip_16e/outputs/2025-12-04/10-18-21
      save_last: true
    - _target_: nequip.train.callbacks.TF32Scheduler
      schedule:
        0: true
  global_options:
    allow_tf32: false
  runs:
  - train
  - test
  training_module:
    _target_: nequip.train.EMALightningModule
    loss:
      _target_: nequip.train.EnergyForceLoss
      per_atom_energy: true
      coeffs:
        total_energy: 1.0
        forces: 1.0
    val_metrics:
      _target_: nequip.train.EnergyForceMetrics
      coeffs:
        total_energy_rmse: 1.0
        per_atom_energy_rmse: null
        forces_rmse: 1.0
        total_energy_mae: null
        per_atom_energy_mae: null
        forces_mae: null
    test_metrics:
      _target_: nequip.train.EnergyForceMetrics
      coeffs:
        total_energy_rmse: 1.0
        per_atom_energy_rmse: null
        forces_rmse: 1.0
        total_energy_mae: null
        per_atom_energy_mae: null
        forces_mae: null
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.001
    lr_scheduler:
      scheduler:
        _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
        factor: 0.6
        patience: 25
        min_lr: 0.0001
        threshold: 0.02
        threshold_mode: rel
      monitor: val0_epoch/weighted_sum
      interval: epoch
      frequency: 1
    model:
      _target_: nequip.model.NequIPGNNModel
      avg_num_neighbors: 89.01878932696137
      per_type_energy_shifts: -5.201448296064995
      per_type_energy_scales:
        O: 0.8089376256532871
        H: 0.5689998484674563
      seed: 456
      model_dtype: float32
      type_names:
      - O
      - H
      r_max: 6.0
      num_features: 128
      num_layers: 2
      l_max: 1
      parity: true
      pair_potential:
        _target_: nequip.nn.pair_potential.ZBL
        units: metal
        chemical_species:
        - O
        - H
      compile_mode: compile
ema_decay: 0.999
